name: Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v7

    - name: Versions
      shell: bash
      run: |
        rustup --version
        cargo --version
        rustc --version

    - name: Cache
      uses: actions/cache@v6
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      
    - name: Build debug [msvc]
      run: cargo build --verbose --features console,tex
      
    - name: Build release [msvc]
      run: cargo build --verbose --features tex --release

    - name: Create zips
      shell: bash
      run: |
        python3 - <<'!EOF'
        from zipfile import ZipFile, ZIP_DEFLATED

        with ZipFile("blur-hook-rs-debug.zip", "w", compression=ZIP_DEFLATED) as zf:
            zf.write("./target/i686-pc-windows-msvc/debug/d3d9.dll", "d3d9.dll")
            zf.write("./target/i686-pc-windows-msvc/debug/d3d9.pdb", "d3d9.pdb")

        with ZipFile("blur-hook-rs-release.zip", "w", compression=ZIP_DEFLATED) as zf:
            zf.write("./target/i686-pc-windows-msvc/release/d3d9.dll", "d3d9.dll")

        !EOF

    - name: Upload artifact
      uses: actions/upload-artifact@v7
      with:
        name: windows-build
        path: |
          ./blur-hook-rs-debug.zip
          ./blur-hook-rs-release.zip

    - name: Publish to GitHub releases
      env:
        GH_TOKEN: ${{ github.token }}
      shell: bash
      run: |
        gh release create "${EPOCHREALTIME}-build-${GITHUB_SHA}" \
          ./blur-hook-rs-debug.zip \
          ./blur-hook-rs-release.zip \
          --title "$TAG" \
          --notes "Automated build artifacts" \
          --prerelease
