name: Blur-hooks-rs Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v4
      
    - name: Install nightly
      run: |
        rustup toolchain install nightly-x86_64-pc-windows-msvc
        rustup default nightly

    - name: Build debug [msvc]
      run: cargo +nightly build --verbose --target=i686-pc-windows-msvc
      
    - name: Build release [msvc]
      run: cargo +nightly build --verbose --release --target=i686-pc-windows-msvc
      
    - name: Collect debug artifact
      uses: actions/upload-artifact@v3
      with:
        name: blur-hook-rs_debug
        path: |
          ./target/i686-pc-windows-msvc/debug/d3d9.dll
          ./target/i686-pc-windows-msvc/debug/d3d9.pdb

    - name: Collect release artifact
      uses: actions/upload-artifact@v3
      with:
        name: blur-hook-rs_release
        path: |
          ./target/i686-pc-windows-msvc/release/d3d9.dll
